WITH RECURSIVE ECOLI_GENERATION AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT
        E.ID,
        E.PARENT_ID,
        EG.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN ECOLI_GENERATION EG
        ON E.PARENT_ID = EG.ID
)

SELECT
    COUNT(*) AS COUNT,
    GENERATION
FROM ECOLI_GENERATION
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;